---

- name: Installing packages with APT
  apt:
    pkg:
      - "openssl"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Installing packages with PACMAN
  pacman:
    pkg:
      - openssl
    state: present
  when: ansible_pkg_mgr == 'pacman'

- name: Installing packages with YUM
  yum:
    name:
      - openssl
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: Creating certs dir
  include_tasks: create_dir.yml
  vars:
    item: "{{ openssl_certs_path }}"
    mode: "0755"

- name: Creating keys dir
  include_tasks: create_dir.yml
  vars:
    item: "{{ openssl_keys_path }}"
    mode: "0700"
