---
- include_tasks: install.yml
  tags:
    - system
    - openssl
    - install
    - openssl-install

- include_tasks: config.yml
  tags:
    - system
    - openssl
    - config
    - openssl-config

- include_tasks: manage.yml
  tags:
    - system
    - openssl
    - manage
    - openssl-manage
